version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=teste-excellent
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: teste-excellent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
